#!/usr/bin/env bash
--#!/usr/bin/env bash

apack reliz.zip 

addline2mesh.lua
ansicolors2.lua


ansicolors.lua

argparse.lua
binds.lua

box2dtool.lua
breaks.txt
build
button.lua


camera.lua
cameratool.lua
caustic
celltool.lua
clear
clone-module.lua

colorselector.lua
common.lua

compat53
compile
conf.lua
coroprocessor.lua

debug.lua
drawing_bitmap.lua
example2.lua

example.lua

fonts
_
gfx
hexfield.lua

hotkeystool.lua
hsx.lua
i18n

imgui.dll

imgui-old.dll
imgui.so
_
include
index.md

inspect.lua
install-scene

inter.lua

jprof.lua
keyconfig.lua

kons.lua

lib_fractaltree
lib_fractaltree_backup
list.lua

logging.orig.lua
_
log.lua
log-thread.lua

love

love-imgui-d.dll
love-imgui.dll
lua51.dll
main.lua
make-android-apk

marshal.so
matrix.lua
matrix.md
menu.lua
MessagePack.lua

mobdebug.lua
.bak
neural_network.lua
NeuralNetwork.lua
nohup.out
packaging.md
particlestool.lua

profi.lua
publish
pull_scripts.sh
qtree.lua
readme.md
readme.tex.md
render_scene.lua
run
run.bat
runc
rundbg
run-example
scale.lua

scenes
scenes.lua

scenetool.lua

serpent.lua
ship.lua
shiptool.lua

struct.lua
tabular.lua
terrain.lua
terraintool.lua
testing.lua


Timer.lua
tlconfig.lua
tools.lua

update-imgui-bindigs
vector-light.lua

vector.lua

