#!/usr/bin/env lua
local parser = require "argparse"()
local inspect = require "inspect"
local args = parser:parse()

--[[
Добавить команды:
    run
    runc
    build
--]]

-- run scne_name
local run_command = parser:command "run"
run_command:argument "scene"

print(inspect(run_command))
