# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  diamond_and_square_config = debug
  messenger_config = debug
  messenger2_config = debug
  messenger3_config = debug
endif
ifeq ($(config),release)
  diamond_and_square_config = release
  messenger_config = release
  messenger2_config = release
  messenger3_config = release
endif

PROJECTS := diamond_and_square messenger messenger2 messenger3

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

diamond_and_square:
ifneq (,$(diamond_and_square_config))
	@echo "==== Building diamond_and_square ($(diamond_and_square_config)) ===="
	@${MAKE} --no-print-directory -C . -f diamond_and_square.make config=$(diamond_and_square_config)
endif

messenger:
ifneq (,$(messenger_config))
	@echo "==== Building messenger ($(messenger_config)) ===="
	@${MAKE} --no-print-directory -C . -f messenger.make config=$(messenger_config)
endif

messenger2:
ifneq (,$(messenger2_config))
	@echo "==== Building messenger2 ($(messenger2_config)) ===="
	@${MAKE} --no-print-directory -C . -f messenger2.make config=$(messenger2_config)
endif

messenger3:
ifneq (,$(messenger3_config))
	@echo "==== Building messenger3 ($(messenger3_config)) ===="
	@${MAKE} --no-print-directory -C . -f messenger3.make config=$(messenger3_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f diamond_and_square.make clean
	@${MAKE} --no-print-directory -C . -f messenger.make clean
	@${MAKE} --no-print-directory -C . -f messenger2.make clean
	@${MAKE} --no-print-directory -C . -f messenger3.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   diamond_and_square"
	@echo "   messenger"
	@echo "   messenger2"
	@echo "   messenger3"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"