# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  diamond_and_square_config = debug
endif
ifeq ($(config),release)
  diamond_and_square_config = release
endif

PROJECTS := diamond_and_square

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

diamond_and_square:
ifneq (,$(diamond_and_square_config))
	@echo "==== Building diamond_and_square ($(diamond_and_square_config)) ===="
	@${MAKE} --no-print-directory -C . -f diamond_and_square.make config=$(diamond_and_square_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f diamond_and_square.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   diamond_and_square"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"