#!/usr/bin/env bash
#TL="~/projects/tl-master/tl"
TL="tl"
echo "Teal version "$($TL --version)
#eval $TL build && love . $1 $2 $3
love . $1 $2 $3
#eval $TL --wdisable unused build && love . $1 $2 $3
#tl build && nlove .
