#!/usr/bin/env bash

TL="tl"
eval $TL --version

make_things()
{
    if [[ $# -eq 0 ]] ; then
        echo "No scene name for love"
        exit 1
    fi

    build_mode="release"

    # Сборка новых аргументов что-бы выкинуть ключ --debug из списка.
    for i in "$@" ; do
        if [[ $i == "--debug" ]] ; then
            build_mode="debug"
        else
            newparams+=("$i")
        fi
    done
   
    # Установка новых аргуметов функции
    set -- "${newparams[@]}" 

    # Распечатать аргументы функции
    #for i in "$@" ; do
        #echo "$i"
    #done

    # Генерация lua кода из teal кода
    local tl_build="$TL build"
    echo $tl_build
    local teal_result=$?

    #eval $TL build && love . $1 $2 $3
    #eval $TL build && love . $1 $2 $3
    #if test $Tl -eq 0; then
    #$TL="tl build"
    #echo "res"$t1
    #echo $t1
    #eval $TL --wdisable unused build && love . $1 $2 $3
    #tl build && nlove .

    echo $@
    pushd scenes/$@
    echo "mode: $build_mode"
    # проверяю вызов команды сборки на успешность завершения
    if ! make config=$build_mode; then
        exit
    fi
    popd

    #readelf -Ws --dyn-syms ddd.so | grep open

    if [[ teal_result -eq 0 ]]; then
        echo 'compiled.'
        love . "$@"
    else
        echo 'not compiled.'
    fi

}

make_things "$@"
