#!/usr/bin/env bash

#TL="tl"
#TL="$HOME/projects/tl/tl"
TL="tl"
eval $TL --version

function0()
{
    #(tl build)
    local tl_build="$TL build"
    echo $tl_build
    #($tl_build)
    $tl_build
    local teal_result=$?

    #(exit 0)
    #(exit 1)
    #(exit -1)
    #TL="~/projects/tl-master/tl"
    #eval $TL build && love . $1 $2 $3
    #eval $TL build && love . $1 $2 $3
    #if test $Tl -eq 0; then
    #$TL="tl build"
    #echo "res"$t1
    #echo $t1
    #eval $TL --wdisable unused build && love . $1 $2 $3
    #tl build && nlove .

    if [[ teal_result -eq 0 ]]; then
        echo 'compiled.'
        love . "$@"
    else
        echo 'not compiled.'
    fi
}

#function0 "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
function0 "$@"
